name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test-input:
        description: 'Test input variable'
        required: false
        default: 'Hello from workflow_dispatch'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Custom Action
        uses: ./ # Uses the action.yml in the root directory 
        with:
          test-input: ${{ inputs.test-input }}
